// Regenerates packages/core/data/cities.seed.sql from data/cities.ts.
// Usage: node scripts/generateCitySeed.mjs
// The SQL block is pasted verbatim into the cities migration; data/cities.spec.ts
// fails when the seed and the dataset drift apart.
import { readFileSync, writeFileSync } from 'node:fs';

const METRO_CITIES = new Set([
  'moscow',
  'spb',
  'nizhny_novgorod',
  'kazan',
  'novosibirsk',
  'samara',
  'yekaterinburg',
]);

const source = readFileSync(new URL('../data/cities.ts', import.meta.url), 'utf8');
const rowPattern =
  /code: '([a-z0-9_]+)',\s*nameRu: '([^']+)',\s*nameEn: '([^']+)',\s*population: (\d+),\s*latitude: (-?[\d.]+),\s*longitude: (-?[\d.]+)/g;

const sqlString = value => `'${value.replace(/'/g, "''")}'`;
const rows = [...source.matchAll(rowPattern)].map(
  ([, code, nameRu, nameEn, population, latitude, longitude]) =>
    `  (${sqlString(code)}, ${sqlString(nameRu)}, ${sqlString(nameEn)}, ${METRO_CITIES.has(code)}, ${population}, ${latitude}, ${longitude})`
);

if (rows.length === 0) throw new Error('No city rows parsed from data/cities.ts');

const sql =
  `-- Generated by scripts/generateCitySeed.mjs from data/cities.ts — do not edit by hand.\n` +
  `INSERT INTO public.cities (code, name_ru, name_en, has_metro, population, latitude, longitude) VALUES\n` +
  `${rows.join(',\n')}\n` +
  `ON CONFLICT (code) DO UPDATE SET\n` +
  `  name_ru = EXCLUDED.name_ru,\n  name_en = EXCLUDED.name_en,\n  has_metro = EXCLUDED.has_metro,\n` +
  `  population = EXCLUDED.population,\n  latitude = EXCLUDED.latitude,\n  longitude = EXCLUDED.longitude;\n`;

writeFileSync(new URL('../data/cities.seed.sql', import.meta.url), sql);
process.stdout.write(`Wrote ${rows.length} city rows to data/cities.seed.sql\n`);
